<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DanhSachMonHocSeeder extends Seeder
{
    public function run()
    {
        $records = [
            [
                'MaMonHoc' => 'MH001',
                'TenMon' => 'Toán Đại Cương',
                'SoTin' => 3,
                'LoaiMonHoc' => 'Bắt buộc',
                'Nganh_ID' => 1,
                'SoTiet' => 45,
                'GhiChu' => null,
                'CREATEO_BY' => 'admin',
                'CREATEO_DATE' => now(),
                'UPDATEO_BY' => 'admin',
                'UPDATEO_DATE' => now(),
                'DELETEO_BY' => null,
                'DELETEO_DATE' => null,
            ],
            [
                'MaMonHoc' => 'MH002',
                'TenMon' => 'Lập Trình Web',
                'SoTin' => 4,
                'LoaiMonHoc' => 'Bắt buộc',
                'Nganh_ID' => 1,
                'SoTiet' => 60,
                'GhiChu' => null,
                'CREATEO_BY' => 'admin',
                'CREATEO_DATE' => now(),
                'UPDATEO_BY' => 'admin',
                'UPDATEO_DATE' => now(),
                'DELETEO_BY' => null,
                'DELETEO_DATE' => null,
            ],
            [
                'MaMonHoc' => 'MH003',
                'TenMon' => 'Cơ Sở Dữ Liệu',
                'SoTin' => 3,
                'LoaiMonHoc' => 'Bắt buộc',
                'Nganh_ID' => 2,
                'SoTiet' => 45,
                'GhiChu' => null,
                'CREATEO_BY' => 'admin',
                'CREATEO_DATE' => now(),
                'UPDATEO_BY' => 'admin',
                'UPDATEO_DATE' => now(),
                'DELETEO_BY' => null,
                'DELETEO_DATE' => null,
            ],
            [
                'MaMonHoc' => 'MH004',
                'TenMon' => 'Mạng Máy Tính',
                'SoTin' => 3,
                'LoaiMonHoc' => 'Bắt buộc',
                'Nganh_ID' => 2,
                'SoTiet' => 45,
                'GhiChu' => null,
                'CREATEO_BY' => 'admin',
                'CREATEO_DATE' => now(),
                'UPDATEO_BY' => 'admin',
                'UPDATEO_DATE' => now(),
                'DELETEO_BY' => null,
                'DELETEO_DATE' => null,
            ],
            [
                'MaMonHoc' => 'MH005',
                'TenMon' => 'Kỹ Thuật Lập Trình',
                'SoTin' => 3,
                'LoaiMonHoc' => 'Bắt buộc',
                'Nganh_ID' => 3,
                'SoTiet' => 45,
                'GhiChu' => null,
                'CREATEO_BY' => 'admin',
                'CREATEO_DATE' => now(),
                'UPDATEO_BY' => 'admin',
                'UPDATEO_DATE' => now(),
                'DELETEO_BY' => null,
                'DELETEO_DATE' => null,
            ],
            [
                'MaMonHoc' => 'MH006',
                'TenMon' => 'Giải Tích',
                'SoTin' => 4,
                'LoaiMonHoc' => 'Bắt buộc',
                'Nganh_ID' => 3,
                'SoTiet' => 60,
                'GhiChu' => null,
                'CREATEO_BY' => 'admin',
                'CREATEO_DATE' => now(),
                'UPDATEO_BY' => 'admin',
                'UPDATEO_DATE' => now(),
                'DELETEO_BY' => null,
                'DELETEO_DATE' => null,
            ],
            [
                'MaMonHoc' => 'MH007',
                'TenMon' => 'Hệ Điều Hành',
                'SoTin' => 3,
                'LoaiMonHoc' => 'Bắt buộc',
                'Nganh_ID' => 4,
                'SoTiet' => 45,
                'GhiChu' => null,
                'CREATEO_BY' => 'admin',
                'CREATEO_DATE' => now(),
                'UPDATEO_BY' => 'admin',
                'UPDATEO_DATE' => now(),
                'DELETEO_BY' => null,
                'DELETEO_DATE' => null,
            ],
            [
                'MaMonHoc' => 'MH008',
                'TenMon' => 'Nhập Môn Lập Trình',
                'SoTin' => 2,
                'LoaiMonHoc' => 'Tự chọn',
                'Nganh_ID' => 4,
                'SoTiet' => 30,
                'GhiChu' => null,
                'CREATEO_BY' => 'admin',
                'CREATEO_DATE' => now(),
                'UPDATEO_BY' => 'admin',
                'UPDATEO_DATE' => now(),
                'DELETEO_BY' => null,
                'DELETEO_DATE' => null,
            ],
            [
                'MaMonHoc' => 'MH009',
                'TenMon' => 'Tư Duy Logic',
                'SoTin' => 2,
                'LoaiMonHoc' => 'Tự chọn',
                'Nganh_ID' => 5,
                'SoTiet' => 30,
                'GhiChu' => null,
                'CREATEO_BY' => 'admin',
                'CREATEO_DATE' => now(),
                'UPDATEO_BY' => 'admin',
                'UPDATEO_DATE' => now(),
                'DELETEO_BY' => null,
                'DELETEO_DATE' => null,
            ],
            [
                'MaMonHoc' => 'MH010',
                'TenMon' => 'Khoa Học Máy Tính',
                'SoTin' => 3,
                'LoaiMonHoc' => 'Tự chọn',
                'Nganh_ID' => 5,
                'SoTiet' => 45,
                'GhiChu' => null,
                'CREATEO_BY' => 'admin',
                'CREATEO_DATE' => now(),
                'UPDATEO_BY' => 'admin',
                'UPDATEO_DATE' => now(),
                'DELETEO_BY' => null,
                'DELETEO_DATE' => null,
            ]
        ];

        DB::table('danhsach_monhoc')->insert($records);
    }
}
